name: FirstJoinUI
version: 1.1.2
api: [3.0.0, 4.0.0]
author: efor89
main: firstjoinui\Main
commands:
  fjoin:
    description: §bFirstJoinUI test open!
permissions:
  firstjoinui.command:
    default: op