name: FirstJoinUI
version: 1.3.0
api: [3.0.0, 4.0.0]
author: efor89
main: firstjoinui\Main
commands:
  fjoin:
    description: §bFirstJoinUI test open!
  jtext:
    description: §bset FirstJoinUI text!
  jtitle:
    description: §bset FirstJoinUI title!
permissions:
  firstjoinui.command:
    default: op
